# pyrefly: ignore [missing-import]
from ray import serve
# pyrefly: ignore [missing-import]
from fastapi import FastAPI

app = FastAPI()

@serve.deployment(num_replicas=2, ray_actor_options={"num_gpus": 0.5})
@serve.ingress(app)
class WeakModelDeployment:
    def __init__(self):
        # Load local 7B/8B model
        print("Weak Model initialized on fractional GPU")

    @app.post("/generate")
    def generate(self, prompt: str):
        return {"response": f"Generated by Weak Model for prompt: {prompt}"}

# Entrypoint for Ray Serve
# serve.run(WeakModelDeployment.bind())
